apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-jenkins
  namespace: default
spec:
  selector:
    matchLabels:
      nginx: web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080