apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      nginx: web
  template:
    metadata: 
      labels:
        nginx: web
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports:
          - containerPort: 80
